[package]
name = "yield_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
inkwell = { version = "0.4.0", features = ["llvm17-0"] }
nom = "7.1.3"
thiserror = "1.0.59"
